name: Notify on GitHub Action Run

on:
  push:
    branches:
      - main
  workflow_run:
    workflows: ["Auth Microservice"]
    types: [completed]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Email Notification
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          from: ${{ secrets.EMAIL_FROM }}
          to: ${{ secrets.EMAIL_TO }}
          subject: "GitHub Action Notification: ${{ github.repository }}"
          body: "Workflow completed with status: ${{ github.event.workflow_run.conclusion }}\nSee details: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          secure: true
